services:
  api:
    build: api
    ports:
      - "3333:3333"
  frontend:
    build: frontend
    ports:
      - "3000:3000"
  db:
    image: mysql:8.4.0
    cap_add:
      - SYS_NICE
    restart: always
    env_file:
      - path: api/.env
    # enviroment:
    #   - 
    ports: 
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
volumes:
  db: 
    driver: local