services:
  web:
    build: .
    ports:
      - "3333:3333"
  db:
    image: mysql:8.4.0
    cap_add:
      - SYS_NICE
    restart: always
    env_file:
      - path: .env
    ports: 
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initb.d/init.sql
volumes:
  db: 
    driver: local